/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jSelolaskuri;


import javax.swing.JOptionPane;
/* Käytössä:    JOptionPane.showMessageDialog(null, 
                        "ALERT MESSAGE", 
                        "TITLE", 
                        JOptionPane.WARNING_MESSAGE);
*/
import java.awt.Color; // Käytössä: setForeground(Color.RED) or (Color.BLACK)
/* font = font.deriveFont(
                Collections.singletonMap(
                    TextAttribute.WEIGHT, TextAttribute.WEIGHT_REGULAR));
*/
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Collections;

import java.awt.event.KeyEvent;  // KeyEvent.VK_UP   .VK_DOWN
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;  // Arrays.asList


/**
 *
 * @author Ismo
 * 
 * NetBeans IDE 8.2
 * 
 *  21.11.2017   Aloitettu. Tavoitteena samanlainen ohjelma, jonka tein C#:lla aiemmin.
 *               Lomakkeet, tarkistukset ja laskenta. -> Toimii!
 *  22.11.2017   Koodin siistimistä ja optimointia, kommenttien lisäämistä,
 *               Virhetilanteiden käsittely: näytä virheellisen kentän sisältö
 *               punaisena virheilmoituksen ajan. Jos siihen oli syötetty
 *               yli 4 merkkiä, niin tyhjennä kenttä.
 * 
 *  29.11.2017   Lomakkeen muotoilua vastaamaan C#-versiota.
 *               Laita samaan ryhmään kuuluvat kentät samaan paneeliin, niin
 *               niitä on helppo järjestellä. Painonapit omaansa.
 *               Jos kenttä on tuloskenttä, niin Focusable ja Editable pois päältä.
 *               Miettimisaika väh. 90 min   Selected päälle.
 *               Kenttien Auto resizing pois päältä.
 * 
 * Aloitettu uudestaan luomalla uusi projekti ja paketin nimi jSelolaskuri.
 * Design ja koodi oli mahdollista kopioida vanhasta, joten nyt uudella projektin
 * nimellä paremmin alkuun.
 * 
 * Luotu tiedosto "seloPelaaja.java", jossa on luokka seloPelaaja.
 * Sinne siirretään kaikki pelaajaan ja laskentaan liittyvät muuttujat ja rutiinit.
 * Päämoduuliin jää vain käyttöliittymän käsittely, kenttien tarkastus ja
 * tuloksien näyttäminen.
 * 
 * Toimii!
 * 
 * 
 *  30.11.2017    Pikashakin laskennan ajaksi vaihda tekstit SELO -> PELO
 *                Myös korostetaan pikashakin tulosten syöttöohjetta
 *                  -> TextAttribute.WEIGHT_BOLD
 *                Täydennetty virheilmoituksiin puuttuneita rajoja, esim. MIN_SELO - MAX_SELO.
 *                Laskenta Enter-napilla, kun ollaan vastustajan SELO-kentässä.
 * 
 * 
 * 
 * 
 * TODO:  koodi ei ole Java-koodaustyylin mukaista kaikin puolin.
 *        Aliohjelmiakin pitäisi jakaa pienempiin osiin.
 *        Tämä on ensimmäinen Java-ohjelmani ja muutan tätä vielä paljonkin,
 *        kun keksin, miten asioita kannattaa tehdä. Mm. radiobuttonien
 *        käsittely ei ehkä vielä ole kunnossa.
 * 
 * 
 */
public class JavaSelolaskuri extends javax.swing.JFrame {
    
    // vakiot, SELO-rajat, pelimäärä
    static final int MIN_SELO = 1000;
    static final int MAX_SELO = 2999;
    static final int MIN_PELIMAARA = 0;
    static final int MAX_PELIMAARA = 9999;
    
    // XXX: miten toteutetaan tekstikentän syötteen maksimipituus?
    static final int MAX_PITUUS = 5; 
    static final int SELO_PITUUS = 4;
    
    // Luodaan shakinpelaaja, jolla tietoina mm. SELO ja pelimäärä.
    // Uudella pelaajalla SELO 1525, pelimäärä 0
    // Nämä arvot kopioidaan käyttöön, jos valitaan "Käytä uutta SELOa jatkolaskennassa"
    // ilman, että on suoritettu laskentaa sitä ennen.
    seloPelaaja shakinpelaaja = new seloPelaaja(1525, 0);
    
    /**
     * Creates new form JavaSelolaskuri
     */
    public JavaSelolaskuri() {
        initComponents();

        // aloita oma selo-kentästä!
        nykyinenSelo_input.requestFocus();
    }
    
   
    //private boolean pelimaara_tyhja = true;
    //private int talteenUusiSelo;
    //private int talteenUusiPelimaara;

    private int nykyinenSelo;
    private int pelimaara;
    private int vastustajanSelo;
    private int pisteet;    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        OmaVahvuusluku_teksti = new javax.swing.JLabel();
        nykyinenSelo_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pelimaara_input = new javax.swing.JTextField();
        VastustajanVahvuusluku_teksti = new javax.swing.JLabel();
        vastustajanSelo_input = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TuloksetPistemaaranKanssa_teksti = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        laskeUusiSelo_button = new javax.swing.JButton();
        kaytaUutta_button = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        UusiSELO_teksti = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uusiSelo_output = new javax.swing.JTextField();
        uusi_pelimaara_output = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        seloEro_output = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        odotustulos_output = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kerroin_output = new javax.swing.JTextField();
        uusiSelo_diff_output = new javax.swing.JTextField();
        vaihteluvali_output = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        keskivahvuus_output = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tulos_output = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        miettimisaika_vah90_Button = new javax.swing.JRadioButton();
        miettimisaika_60_89_Button = new javax.swing.JRadioButton();
        miettimisaika_15_59_Button = new javax.swing.JRadioButton();
        miettimisaika_alle15_Button = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        voittoRadioButton_input = new javax.swing.JRadioButton();
        tappioRadioButton_input = new javax.swing.JRadioButton();
        tasapeliRadioButton_input = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OmaVahvuusluku_teksti.setText("Nykyinen SELO (1000-2999)");

        jLabel3.setText("Pelimäärä (numero tai tyhjä, 0-10, jos uusi pelaaja)");

        VastustajanVahvuusluku_teksti.setText("Vastustajan SELO. Tai monta tuloksineen: +1725 -1810 =1612 (tai 1612)");

        vastustajanSelo_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vastustajanSelo_inputKeyPressed(evt);
            }
        });

        jLabel13.setText("Montaa vahvuuslukua syötettäessä voitto +  tasapeli = tai tyhjä  ja tappio -");

        TuloksetPistemaaranKanssa_teksti.setText("Tai pistemäärä ja vastustajien SELOt: 1.5 1725 1810 1612");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OmaVahvuusluku_teksti)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(nykyinenSelo_input, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pelimaara_input, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addComponent(VastustajanVahvuusluku_teksti)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(TuloksetPistemaaranKanssa_teksti)))
                    .addComponent(vastustajanSelo_input, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OmaVahvuusluku_teksti)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nykyinenSelo_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pelimaara_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VastustajanVahvuusluku_teksti, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vastustajanSelo_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TuloksetPistemaaranKanssa_teksti)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Shakin vahvuusluvun laskenta");

        laskeUusiSelo_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        laskeUusiSelo_button.setText("Laske uusi SELO");
        laskeUusiSelo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laskeUusiSelo_buttonActionPerformed(evt);
            }
        });

        kaytaUutta_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kaytaUutta_button.setText("Käytä uutta SELOa jatkolaskennassa");
        kaytaUutta_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaytaUutta_buttonActionPerformed(evt);
            }
        });

        jLabel12.setText("Java 29.11.2017 Ismo Suihko github/isuihko");

        UusiSELO_teksti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UusiSELO_teksti.setText("Uusi SELO");

        jLabel8.setText("Uusi pelimäärä");

        uusiSelo_output.setEditable(false);
        uusiSelo_output.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uusiSelo_output.setFocusable(false);
        uusiSelo_output.setRequestFocusEnabled(false);

        uusi_pelimaara_output.setEditable(false);
        uusi_pelimaara_output.setFocusable(false);

        jLabel9.setText("Piste-ero");

        seloEro_output.setEditable(false);
        seloEro_output.setFocusable(false);

        jLabel10.setText("Odotustulos");

        odotustulos_output.setEditable(false);
        odotustulos_output.setFocusable(false);

        jLabel11.setText("Kerroin");

        kerroin_output.setEditable(false);
        kerroin_output.setFocusable(false);

        uusiSelo_diff_output.setEditable(false);
        uusiSelo_diff_output.setFocusable(false);

        vaihteluvali_output.setEditable(false);
        vaihteluvali_output.setFocusable(false);

        jLabel15.setText("Vastustajien keskivahvuus");

        keskivahvuus_output.setEditable(false);
        keskivahvuus_output.setFocusable(false);

        jLabel16.setText("Ottelun/turnauksen tulos");

        tulos_output.setEditable(false);
        tulos_output.setFocusable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UusiSELO_teksti)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(uusiSelo_output, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uusiSelo_diff_output, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vaihteluvali_output, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uusi_pelimaara_output, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(keskivahvuus_output)
                            .addComponent(tulos_output))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kerroin_output, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(odotustulos_output, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seloEro_output, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UusiSELO_teksti)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vaihteluvali_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uusiSelo_diff_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uusiSelo_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(seloEro_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uusi_pelimaara_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(odotustulos_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(keskivahvuus_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(kerroin_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tulos_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setText("Miettimisaika:");

        miettimisaika_vah90_Button.setSelected(true);
        miettimisaika_vah90_Button.setText("väh. 90 min");
        miettimisaika_vah90_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miettimisaika_vah90_ButtonActionPerformed(evt);
            }
        });

        miettimisaika_60_89_Button.setText("60-89 min");
        miettimisaika_60_89_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miettimisaika_60_89_ButtonActionPerformed(evt);
            }
        });

        miettimisaika_15_59_Button.setText("15-59 min");
        miettimisaika_15_59_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miettimisaika_15_59_ButtonActionPerformed(evt);
            }
        });

        miettimisaika_alle15_Button.setText("alle 15 min");
        miettimisaika_alle15_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miettimisaika_alle15_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miettimisaika_vah90_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miettimisaika_60_89_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miettimisaika_15_59_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(miettimisaika_alle15_Button)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(miettimisaika_vah90_Button)
                    .addComponent(miettimisaika_60_89_Button)
                    .addComponent(miettimisaika_15_59_Button)
                    .addComponent(miettimisaika_alle15_Button))
                .addContainerGap())
        );

        jLabel6.setText("Ottelun tulos:");

        voittoRadioButton_input.setText("1=voitto");
        voittoRadioButton_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voittoRadioButton_inputActionPerformed(evt);
            }
        });
        voittoRadioButton_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                voittoRadioButton_inputKeyPressed(evt);
            }
        });

        tappioRadioButton_input.setText("0=tappio");
        tappioRadioButton_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tappioRadioButton_inputActionPerformed(evt);
            }
        });
        tappioRadioButton_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tappioRadioButton_inputKeyPressed(evt);
            }
        });

        tasapeliRadioButton_input.setText("1/2=tasapeli");
        tasapeliRadioButton_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasapeliRadioButton_inputActionPerformed(evt);
            }
        });
        tasapeliRadioButton_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tasapeliRadioButton_inputKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voittoRadioButton_input)
                    .addComponent(tasapeliRadioButton_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tappioRadioButton_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tappioRadioButton_input))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasapeliRadioButton_input)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voittoRadioButton_input))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(laskeUusiSelo_button))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(kaytaUutta_button)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(laskeUusiSelo_button)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(kaytaUutta_button)
                .addGap(4, 4, 4)
                .addComponent(jLabel12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //  KENTTIEN TARKASTUKSET

    // Nämä valintapainikkeet ovat omana ryhmänään paneelissa
    // Käynnistyksessä valitaan oletukseksi vähintään 90 min.
    // Magic numbers:   90, 60, 15, 5
    private void tarkista_miettimisaika()
    {
        if (miettimisaika_vah90_Button.isSelected())
            shakinpelaaja.set_miettimisaika(90);  // vähintään 90 minuuttia (oletus)
        else if (miettimisaika_60_89_Button.isSelected())
            shakinpelaaja.set_miettimisaika(60);  // 60-89 minuuttia
        else if (miettimisaika_15_59_Button.isSelected())
            shakinpelaaja.set_miettimisaika(15);  // 15-59 minuuttia
        else
            shakinpelaaja.set_miettimisaika(5);   // alle 15 minuuttia
    }    

    // Tarkista Oma SELO -kenttä, oltava numero ja rajojen sisällä
    private int tarkista_nykyinenselo()
    {
        int nykyinenSelo;
    
        // remove leading and trailing white spaces
        String tmpstr = nykyinenSelo_input.getText().trim();
        nykyinenSelo_input.setText(tmpstr);
        
        // onko kelvollinen numero?
        try {
            // voitaisiin käsitellä kaikki numerokentät tässä, mutta tehdään
            //  yksitellen, niin saadaan yksilöidyt virhekäsittelyt
            nykyinenSelo = Integer.parseInt(nykyinenSelo_input.getText());
            // nykyinenPelimaara = Integer.parseInt(nykyinenPelimaara_input.getText());
            // vastustajanSelo = Integer.parseInt(vastustajanSelo_input.getText());
        }
        catch (NumberFormatException e) {
            nykyinenSelo = MIN_SELO - 1;
        }
        
        // onko kelvollinen numero?
        if (nykyinenSelo < MIN_SELO || nykyinenSelo > MAX_SELO)
        {
            nykyinenSelo_input.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null,
                    "Nykyisen SELOn oltava numero 1000-2999.",
                    "VIRHE",
                    JOptionPane.WARNING_MESSAGE);
            nykyinenSelo_input.setForeground(Color.BLACK);
            
            if (nykyinenSelo_input.getText().length() > MAX_PITUUS)
                nykyinenSelo_input.setText("");
            nykyinenSelo_input.requestFocus();   // siirry takaisin virheelliseen kenttään
            return -9;
        }        
        return nykyinenSelo;
    }
            

    //
    // tarkista pelimäärä
    // Saa olla tyhjä, mutta jos annettu, oltava numero, joka on 0-9999.
    // Käytetään uuden pelaajan laskentakaavaa, jos pelimäärä on 0-10.
    //
    private int tarkista_pelimaara()
    {
        int pelimaara;
        
        // remove leading and trailing white spaces
        String tmpstr = pelimaara_input.getText().trim();
        pelimaara_input.setText(tmpstr);
        //
        // tarkista Pelimäärä -kenttä
        // Saa olla tyhjä, mutta jos annettu, oltava numero, joka on 0-9999.
        //        
        if (pelimaara_input.getText().isEmpty()) {
           return MIN_PELIMAARA - 1; // OK;
        } else {
            try {
                pelimaara = Integer.parseInt(pelimaara_input.getText());
            }
            catch (NumberFormatException e) {
                pelimaara = MIN_PELIMAARA - 1;  // -> virheilmoitus
            }
        }

        if (pelimaara < MIN_PELIMAARA || pelimaara > MAX_PELIMAARA) {
            pelimaara_input.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null,
                    "pelimäärän oltava numero " + MIN_PELIMAARA + " - " + MAX_PELIMAARA + " tai tyhjä",
                    "VIRHE",
                    JOptionPane.WARNING_MESSAGE);
            pelimaara_input.setForeground(Color.BLACK);
            
            if (pelimaara_input.getText().length() > MAX_PITUUS)
                pelimaara_input.setText("");
            pelimaara_input.requestFocus();   // siirry takaisin virheelliseen kenttään
            return -9;            
        }
        return pelimaara;
    }
    
    // Tarkista Vastustajan SELO -kenttä, oltava numero ja rajojen sisällä
    //
    // Syöte voi olla annettu kolmella eri formaatilla:
    //  1)  1720   -> ja sitten tulos valintanapeilla
    //  2)  +1624 -1700 =1685 +1400    jossa  '+' voitto, '=' tasapeli ja '-' tappio.
    //                                 Tasapeli voidaan myös antaa ilman '='-merkkiä.
    //  3)  2,5 1624 1700 1685 1400    Eli aloitetaan kokonaispistemäärällä.
    //                                 SELOt ilman erillisiä tuloksia.
    //
    // Yhden ottelun tulos voidaan antaa kolmella tavalla:
    //   1)  1720      ja tulos erikseen valintanapeilla, esim. 1/2 tasapeli
    //   2)  =1720     tasapeli myös näin
    //   3)  0.5 1720  tai näin
    //
    
    // XXX:   tarkista_vastustajanSelo() ON LIIAN PITKÄ. JAA OSIIN!
    //
    private int tarkista_vastustajanSelo()
    {
        int vastustajanSelo = 0;
        float syotetty_tulos = 0F;
        
        // remove leading and trailing white spaces
        String tmpstr = vastustajanSelo_input.getText().trim();
        vastustajanSelo_input.setText(tmpstr);            

        if (vastustajanSelo_input.getText().isEmpty()) {
           vastustajanSelo = MIN_SELO - 1;   // ei saa olla tyhjä -> virheilmoitus
        } else if (vastustajanSelo_input.getText().length() == SELO_PITUUS) {
            try {
                vastustajanSelo = Integer.parseInt(vastustajanSelo_input.getText());
            }
            catch (NumberFormatException e) {
                vastustajanSelo = MIN_SELO - 1;  // -> virheilmoitus
            }            
        }
        else
        {         
            // kentässä voidaan antaa alussa turnauksen tulos, esim. 0.5, 2.0, 2.5, 7.5 eli saadut pisteet
            shakinpelaaja.set_syotetty_turnauksen_tulos(-1.0F);  // oletus: ei annettu

            // poista sanojen väleistä ylimääräiset välilyönnit!
            String result = vastustajanSelo_input.getText().replaceAll("\\s+", " ");
            vastustajanSelo_input.setText(result);
            
            // Nyt voidaan jakaa syöte merkkijonoihin!
            String [] selostr = vastustajanSelo_input.getText().split(" ");
            List<String> selo_lista = Arrays.asList(selostr);
            
            int selo1 = MIN_SELO;
            int tulos1 = 0;
            Boolean ensimmainen = true;
            Boolean turnauksen_tulos = false;

            // Tutki vastustajanSelo_input-kenttä
            // Tallenna listaan selo_lista vastustajien SELO:t ja tulokset merkkijonona            
            for (int i = 0; i < selo_lista.size(); i++) {
                String tulos = selo_lista.get(i);
                if (ensimmainen)
                {                    
                    // Tarkista, onko alussa annettu turnauksen lopputulos eli kokonaispistemäärä?
                    ensimmainen = false;
                    try {
                        syotetty_tulos = Float.parseFloat(tulos);
                        if (syotetty_tulos >= 0.0F && syotetty_tulos <= 99.5F)
                        {
                            turnauksen_tulos = true;
                            shakinpelaaja.set_syotetty_turnauksen_tulos(syotetty_tulos);

                            // alussa oli annettu turnauksen lopputulos, jatka SELOjen tarkistamista
                            // Nyt selojen on oltava ilman tulosmerkintää!
                            continue;
                        }
                    }
                    catch (NumberFormatException e) {
                        // OK, anna jatkaa ja jää kiinni myöhemmin
                    }
                }      
                
                
                // merkkijono voi alkaa merkillä '+', '=' tai '-'
                // Mutta tasapeli voidaan antaa myös ilman '='-merkkiä
                // Jos oli annettu turnauksen tulos, niin selot on syötettävä näin ilman tulosta
                if (tulos.length() == SELO_PITUUS)  // numero(4 merkkiä)
                {
                    try {
                        selo1 = Integer.parseInt(tulos);
                    }
                    catch (NumberFormatException e) {
                        selo1 = MIN_SELO - 1;  // -> virheilmoitus, ei ollut numero
                        break;                    
                    }
                    tulos1 = 1;  // 1=tasapeli  HUOM! Jos tulos oli jo annettu, niin tätä ei huomioida laskuissa
                    shakinpelaaja.lista_lisaa_ottelun_tulos(selo1, tulos1);
                }
                else if (tulos.length() == MAX_PITUUS && turnauksen_tulos == false)  // tulos(1 merkki)+numero(4 merkkiä)
                {
                    // Erillisten tulosten antaminen hyväksytään vain, jos turnauksen
                    // lopputulosta ei oltu jo annettu
                    char c = tulos.charAt(0);
                    
                    switch (c)
                    {
                        case '+':   // voitto 1 piste, tallentetaan 2
                            tulos1 = 2;
                            break;
                        case '=':   // tasapeli 1/2 pistettä, tallentaan 1
                            tulos1 = 1;
                            break;
                        case '-':   // tappio, tallennetaan 0
                            tulos1 = 0;
                            break;
                        default:
                            selo1 = MIN_SELO - 1;  // ei ollut oikea tulos!
                            break;
                    }           

                    if (selo1 >= MIN_SELO)  // Vielä OK?  Selvitä sitten numero
                    {
                        // parse: ohita +=- eli aloita numerosta, oli esim. =1612
                        try {
                            selo1 = Integer.parseInt(tulos.substring(1));
                        }
                        catch (NumberFormatException e) {
                            selo1 = MIN_SELO - 1;  // -> virheilmoitus, ei ollut numero
                            break;                    
                        }
                        shakinpelaaja.lista_lisaa_ottelun_tulos(selo1, tulos1);
                    }
                }
                else
                {
                    // pituus ei ollut SELO_PITUUS (4 esim. 1234) eikä MAX_PITUUS (5 esim. +1234)
                    selo1 = MIN_SELO - 1; // -> virheellistä dataa
                    break;
                }

                // Oliko asetettu virhe, mutta ei vielä poistuttu foreach-loopista?
                if (selo1 < MIN_SELO)
                    break;

            } // foreach

            if (turnauksen_tulos)
            {
                // Syötteen annettu turnauksen tulos ei saa olla suurempi kuin pelaajien lukumäärä
                // Vertailu kokonaislukuina, syötetty tulos 3.5 vs 4, vertailu 7 vs 8.
                if ((int)(2*syotetty_tulos + 0.01F) > 2*shakinpelaaja.get_vastustajien_lkm_listassa())
                {
                    selo1 = MIN_SELO - 2;  // tästä oma virheilmoitus
                }
            }

            // vain virhetarkastusta varten
            vastustajanSelo = selo1;
        }

        // VIRHEILMOITUKSET
        if (vastustajanSelo < MIN_SELO || vastustajanSelo > MAX_SELO)
        {
          
            vastustajanSelo_input.setForeground(Color.RED);

            if (vastustajanSelo == MIN_SELO - 2) {
                JOptionPane.showMessageDialog(null,
                    "Turnauksen pistemäärä (" + syotetty_tulos + ") voi olla enintään sama kuin vastustajien lukumäärä (" + shakinpelaaja.get_vastustajien_lkm_listassa() + ").",
                    "VIRHE",
                    JOptionPane.WARNING_MESSAGE);           
            } else {
                JOptionPane.showMessageDialog(null,
                    "Vastustajan SELOn oltava numero " + MIN_SELO + " - " + MAX_SELO,
                    "VIRHE",
                    JOptionPane.WARNING_MESSAGE);            
            }
            vastustajanSelo_input.setForeground(Color.BLACK);            

            // Ei tyhjennetä kenttää, jotta sitä on helpompi korjata
            //              if (vastustajanSelo_input.Text.Length > MAX_PITUUS)
            //                  vastustajanSelo_input.Text = "";
            // Kentästä on kuitenkin jo poistettu ylimääräiset välilyönnit
            vastustajanSelo_input.requestFocus();
            return -9;
        }
      
        return vastustajanSelo;
    }

    private int tarkista_ottelun_tulos()
    {
        int pisteet;
    
        // Tarkista ottelun tulos -painikkeet ja tallenna niiden vaikutus
        // pisteet: tappiosta 0, tasapelistä puoli ja voitosta yksi
        //          tallentetaan kokonaisulukuna 0, 1 ja 2
        if (tappioRadioButton_input.isSelected()) {
            pisteet = 0;
        } else if (tasapeliRadioButton_input.isSelected()) {
            pisteet = 1;
        } else if (voittoRadioButton_input.isSelected()) {
            pisteet = 2;
        } else {
            JOptionPane.showMessageDialog(null,
                    "Ottelun tulosta ei ole annettu!",
                    "VIRHE",
                    JOptionPane.WARNING_MESSAGE);
            tappioRadioButton_input.requestFocus();  // siirry ensimmäiseen radiobuttoneista
            return -1;
        }
        return pisteet;
    }
    
    // FUNKTIO: tarkistaInput
    //
    // Tarkistaa
    //      -miettimisaika-valintanapit
    //      -nykyinen SELO eli oma alkuselo
    //      -nykyinen oma pelimäärä
    //      -vastustajan SELO tai vastustajien SELOT
    //      -yhtä ottelua syötettäessä tuloksen valintanapit
    //
    // Tuloksena
    //    palautetaan parametreissa oma selo ja pelimäärä
    //    1) Jos syötetty yksi ottelu, niin palautetaan vastustajan selo ja ottelun pisteet
    //    2) Jos syötetty monen ottelun tulokset, niin selo_lista sisältää selot ja tulokset
    //
    // VIrhetilanteet:
    //    Jos jokin syötekenttä on virheellinen, annetaan virheilmoitus, siirrytään ko kenttään ja keskeytetään.
    //    Kenttiä tarkistetaan yo. järjestyksessä ja vain ensimmäisestä virheestä annetaan virheilmoitus.
    //
    private Boolean tarkistaInput()
    {    
        // ************ TARKISTA SYÖTE ************
      
        // ENSIN TARKISTA MIETTIMISAIKA. Tässä ei voi olla virheellista tietoa.
        tarkista_miettimisaika();

        nykyinenSelo = 0; pelimaara = 0; vastustajanSelo = 0; pisteet = 0;  // alkuarvot

        nykyinenSelo = tarkista_nykyinenselo();
        if (nykyinenSelo == -9)
            return false;

        pelimaara = tarkista_pelimaara();
        if (pelimaara == -9)
            return false;

        vastustajanSelo = tarkista_vastustajanSelo();
        if (vastustajanSelo == -9)
            return false;

        // jos ottelut ovat listassa, niin ottelutuloksen valintanapeilla ei ole merkitystä
        if (shakinpelaaja.get_vastustajien_lkm_listassa() > 0)
            return true;

        pisteet = tarkista_ottelun_tulos();
        if (pisteet < 0)
            return false;        
       
        return true;
    }
    
    private void laskeUusiSelo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laskeUusiSelo_buttonActionPerformed
        if (suorita_laskenta())
            nayta_tulokset();
    }//GEN-LAST:event_laskeUusiSelo_buttonActionPerformed

    
    
    private void kaytaUutta_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaytaUutta_buttonActionPerformed
        int selo = shakinpelaaja.get_uusiselo();
        int pelimaara = shakinpelaaja.get_uusipelimaara();

        if (selo == 0) {
            selo = shakinpelaaja.get_selo();
            pelimaara = shakinpelaaja.get_pelimaara();
        }
            
        nykyinenSelo_input.setText(Integer.toString(selo));
        if (pelimaara > MIN_PELIMAARA - 1) {
            // vain, jos pelimaara oli annettu (muutoin on jo valmiiksi tyhjä)
            pelimaara_input.setText(Integer.toString(pelimaara));
        }
        vastustajanSelo_input.requestFocus();
    }//GEN-LAST:event_kaytaUutta_buttonActionPerformed

    
    private enum vaihda_miettimisaika_enum {VAIHDA_SELOKSI, VAIHDA_PELOKSI };

    private void miettimisaika_vaihda_tekstit(vaihda_miettimisaika_enum suunta)
    {
        String tmpstr;
        String alkup, uusi;

        Font font = TuloksetPistemaaranKanssa_teksti.getFont();
        
        if (suunta == vaihda_miettimisaika_enum.VAIHDA_SELOKSI)
        {
            alkup = "PELO";
            uusi = "SELO";
            
            font = font.deriveFont(
                Collections.singletonMap(
                    TextAttribute.WEIGHT, TextAttribute.WEIGHT_REGULAR));

            TuloksetPistemaaranKanssa_teksti.setFont(font);                        
        }
        else
        {
            alkup = "SELO";
            uusi = "PELO";
            // korosta PELO-ohje


            font = font.deriveFont(
                Collections.singletonMap(
                    TextAttribute.WEIGHT, TextAttribute.WEIGHT_BOLD));

            TuloksetPistemaaranKanssa_teksti.setFont(font);
        }

        tmpstr = OmaVahvuusluku_teksti.getText().replaceAll(alkup, uusi);
        OmaVahvuusluku_teksti.setText(tmpstr);

        tmpstr = VastustajanVahvuusluku_teksti.getText().replaceAll(alkup, uusi);
        VastustajanVahvuusluku_teksti.setText(tmpstr);

        tmpstr = TuloksetPistemaaranKanssa_teksti.getText().replaceAll(alkup, uusi);
        TuloksetPistemaaranKanssa_teksti.setText(tmpstr);

        tmpstr = UusiSELO_teksti.getText().replaceAll(alkup, uusi);
        UusiSELO_teksti.setText(tmpstr);

        tmpstr = laskeUusiSelo_button.getText().replaceAll(alkup, uusi);
        laskeUusiSelo_button.setText(tmpstr);

        tmpstr = kaytaUutta_button.getText().replaceAll(alkup, uusi);
        kaytaUutta_button.setText(tmpstr);   
    }
    
    private void miettimisaika_vah90_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miettimisaika_vah90_ButtonActionPerformed
        miettimisaika_vah90_Button.setSelected(true);
        miettimisaika_60_89_Button.setSelected(false);
        miettimisaika_15_59_Button.setSelected(false);
        miettimisaika_alle15_Button.setSelected(false);
        miettimisaika_vaihda_tekstit(vaihda_miettimisaika_enum.VAIHDA_SELOKSI);
    }//GEN-LAST:event_miettimisaika_vah90_ButtonActionPerformed

    private void miettimisaika_60_89_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miettimisaika_60_89_ButtonActionPerformed
        miettimisaika_vah90_Button.setSelected(false);
        miettimisaika_60_89_Button.setSelected(true);
        miettimisaika_15_59_Button.setSelected(false);
        miettimisaika_alle15_Button.setSelected(false);
        miettimisaika_vaihda_tekstit(vaihda_miettimisaika_enum.VAIHDA_SELOKSI);
    }//GEN-LAST:event_miettimisaika_60_89_ButtonActionPerformed

    private void miettimisaika_15_59_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miettimisaika_15_59_ButtonActionPerformed
        miettimisaika_vah90_Button.setSelected(false);
        miettimisaika_60_89_Button.setSelected(false);
        miettimisaika_15_59_Button.setSelected(true);
        miettimisaika_alle15_Button.setSelected(false);
        miettimisaika_vaihda_tekstit(vaihda_miettimisaika_enum.VAIHDA_SELOKSI);
    }//GEN-LAST:event_miettimisaika_15_59_ButtonActionPerformed

    private void miettimisaika_alle15_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miettimisaika_alle15_ButtonActionPerformed
        miettimisaika_vah90_Button.setSelected(false);
        miettimisaika_60_89_Button.setSelected(false);
        miettimisaika_15_59_Button.setSelected(false);
        miettimisaika_alle15_Button.setSelected(true);
        miettimisaika_vaihda_tekstit(vaihda_miettimisaika_enum.VAIHDA_PELOKSI);
    }//GEN-LAST:event_miettimisaika_alle15_ButtonActionPerformed

    // FUNKTIO: suorita_laskenta()
    //
    // Laske tulokset
    // Näytä tulokset
    private Boolean suorita_laskenta()
    {
        // tyhjennä ottelulista!
        shakinpelaaja.lista_tyhjenna();

        // jos annettu yksi ottelu, niin vastustajan tiedot:
        //     vastustajanSelo ja pisteet
        // jos annettu useampi ottelu, niin ottelut ovat listassa ja get_vastustajien_lkm_listassa > 0
        if (tarkistaInput() == false)
            return false;

        // asettaa omat tiedot, nollaa tilastotiedot ym.
        shakinpelaaja.aloita_laskenta(nykyinenSelo, pelimaara);

        //  *** LASKETAAN ***

        // Lasketaanko yhtä ottelua vai turnausta?
        if (shakinpelaaja.get_vastustajien_lkm_listassa() == 0) // tyhjä lista
            shakinpelaaja.pelaa_ottelu(vastustajanSelo, pisteet); // pelaa yksi tietty ottelu
        else
            shakinpelaaja.pelaa_ottelu();       // pelaa kaikki (turnauksen) ottelut

        return true;
    }

    void nayta_tulokset()
    {
        //  *** NÄYTÄ TULOKSIA ***

        // Laskettiinko yhtä ottelua vai turnausta?
        if (shakinpelaaja.get_vastustajien_lkm_listassa() == 0)
        {
            // tyhjä lista, joten yksi ottelu -> näytä uusi vahvuusluku, pelimäärä ym. tiedot
            String tempstr = Integer.toString(Math.abs(shakinpelaaja.get_selo_alkuperainen() - shakinpelaaja.get_viimeisin_vastustaja()));
            seloEro_output.setText(tempstr);

            odotustulos_output.setText(Float.toString(shakinpelaaja.get_odotustulos() / 100F));
            kerroin_output.setText(Integer.toString(shakinpelaaja.get_kerroin()));
            vaihteluvali_output.setText("");  // ei vaihteluväliä, koska vain yksi luku laskettu
        }
        else
        {
            // tyhjennä yksittäisen ottelun tuloskentät
            seloEro_output.setText("");
            // odotustulos näytetään, jos ei ollut uuden pelaajan laskenta
            if (shakinpelaaja.get_pelimaara() < 0 || shakinpelaaja.get_pelimaara() > 10)
                odotustulos_output.setText(Float.toString(shakinpelaaja.get_odotustuloksien_summa() / 100F));
            else
                odotustulos_output.setText("");

            // kerroin on laskettu alkuperäisestä omasta selosta
            kerroin_output.setText(Integer.toString(shakinpelaaja.get_kerroin()));

            // Valintanapeilla ei merkitystä, kun käsitellään turnausta eli valinnat pois
            tappioRadioButton_input.setSelected(false);
            tasapeliRadioButton_input.setSelected(false);
            voittoRadioButton_input.setSelected(false);

            // Näytä laskennan aikainen vahvuusluvun vaihteluväli
            // Jos oli annettu turnauksen tulos, niin laskenta tehdään yhdellä lauseella eikä vaihteluväliä ole
            // Vaihteluväliä ei ole myöskään, jos oli laskettu yhden ottelun tulosta
            // On vain, jos tulokset formaatissa "+1622 -1880 =1633"
            if (shakinpelaaja.get_syotetty_turnauksen_tulos() < 0 && shakinpelaaja.get_turnauksen_ottelumaara() > 1)
            {
                vaihteluvali_output.setText(
                    Integer.toString(shakinpelaaja.get_min_selo()) + " - " + Integer.toString(shakinpelaaja.get_max_selo()));
            }
            else
                vaihteluvali_output.setText("");  // muutoin siis tyhjä
        }

        // Näytä uusi vahvuusluku ja pelimäärä. Näytä myös vahvuusluvun muutos +/-NN pistettä,
        // sekä vastustajien keskivahvuus ja omat pisteet.
        uusiSelo_output.setText(Integer.toString(shakinpelaaja.get_uusiselo()));
        // How to format as with C#  .ToString("+#;-#;0")
        int i = shakinpelaaja.get_uusiselo() - shakinpelaaja.get_selo_alkuperainen();
        uusiSelo_diff_output.setText(((i > 0) ? "+" : (i < 0) ? "-" : "") + Integer.toString(i));
        if (shakinpelaaja.get_uusipelimaara() >= 0)
            uusi_pelimaara_output.setText(Integer.toString(shakinpelaaja.get_uusipelimaara()));
        else
            uusi_pelimaara_output.setText("");
        keskivahvuus_output.setText(Integer.toString(shakinpelaaja.get_turnauksen_keskivahvuus()));
        // Turnauksen loppupisteet / ottelujen lkm, esim.  2.5 / 6
        // C#  tulos formatoitu, näyttää esim. 2.0 / 3
        tulos_output.setText(
            Float.toString(shakinpelaaja.get_turnauksen_tulos() / 2F) + " / " +
            Integer.toString(shakinpelaaja.get_turnauksen_ottelumaara()));
    }    
    
    
    private void voittoRadioButton_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voittoRadioButton_inputActionPerformed
        tappioRadioButton_input.setSelected(false);
        tasapeliRadioButton_input.setSelected(false);
        voittoRadioButton_input.setSelected(true);
        if (suorita_laskenta())
            nayta_tulokset();
    }//GEN-LAST:event_voittoRadioButton_inputActionPerformed
    
    // Suorita laskenta aina kun siirrytään tulos-painikkeeseen.
    //
    private void voittoRadioButton_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_voittoRadioButton_inputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tasapeliRadioButton_input.requestFocus();
            tappioRadioButton_input.setSelected(false);
            tasapeliRadioButton_input.setSelected(true);
            voittoRadioButton_input.setSelected(false);
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tappioRadioButton_input.requestFocus();
            tappioRadioButton_input.setSelected(true);
            tasapeliRadioButton_input.setSelected(false);
            voittoRadioButton_input.setSelected(false);
        }
        if (suorita_laskenta())
            nayta_tulokset();

        return;
    }//GEN-LAST:event_voittoRadioButton_inputKeyPressed

    private void tappioRadioButton_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tappioRadioButton_inputActionPerformed
        tappioRadioButton_input.setSelected(true);
        tasapeliRadioButton_input.setSelected(false);
        voittoRadioButton_input.setSelected(false);
        if (suorita_laskenta())
            nayta_tulokset();

    }//GEN-LAST:event_tappioRadioButton_inputActionPerformed

    private void tappioRadioButton_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tappioRadioButton_inputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            voittoRadioButton_input.requestFocus();
            tappioRadioButton_input.setSelected(true);
            tasapeliRadioButton_input.setSelected(false);
            voittoRadioButton_input.setSelected(false);
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tasapeliRadioButton_input.requestFocus();
            tappioRadioButton_input.setSelected(false);
            tasapeliRadioButton_input.setSelected(true);
            voittoRadioButton_input.setSelected(false);
        }
        if (suorita_laskenta())
            nayta_tulokset();
    }//GEN-LAST:event_tappioRadioButton_inputKeyPressed

    private void tasapeliRadioButton_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasapeliRadioButton_inputActionPerformed
        tappioRadioButton_input.setSelected(false);
        tasapeliRadioButton_input.setSelected(true);
        voittoRadioButton_input.setSelected(false);
        if (suorita_laskenta())
            nayta_tulokset();

    }//GEN-LAST:event_tasapeliRadioButton_inputActionPerformed

    private void tasapeliRadioButton_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tasapeliRadioButton_inputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tappioRadioButton_input.requestFocus();
            tappioRadioButton_input.setSelected(true);
            tasapeliRadioButton_input.setSelected(false);
            voittoRadioButton_input.setSelected(false);
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            voittoRadioButton_input.requestFocus();
            tappioRadioButton_input.setSelected(false);
            tasapeliRadioButton_input.setSelected(false);
            voittoRadioButton_input.setSelected(true);
        }
        if (suorita_laskenta())
            nayta_tulokset();
    }//GEN-LAST:event_tasapeliRadioButton_inputKeyPressed

    // Suorita laskenta Enter-napilla, kun ollaan vastustajanSelo_input-kentässä
    private void vastustajanSelo_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vastustajanSelo_inputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (suorita_laskenta())
                nayta_tulokset();
        }
    }//GEN-LAST:event_vastustajanSelo_inputKeyPressed


    private void odotustulos_outputActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void kerroin_outputActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void nykyinenSelo_inputActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:

    }                                                  
    
    
    /*
        private void miettimisaika_vaihda_tekstit(vaihda_miettimisaika_enum suunta)
        {
            string tmpstr;
            string alkup, uusi;

            if (suunta == vaihda_miettimisaika_enum.VAIHDA_SELOKSI)
            {
                alkup = "PELO";
                uusi = "SELO";
                TuloksetPistemaaranKanssa_teksti.Font = new Font(TuloksetPistemaaranKanssa_teksti.Font, FontStyle.Regular);
            }
            else
            {
                alkup = "SELO";
                uusi = "PELO";
                // korosta PELO-ohje
                TuloksetPistemaaranKanssa_teksti.Font = new Font(TuloksetPistemaaranKanssa_teksti.Font, FontStyle.Bold);
            }

            tmpstr = OmaVahvuusluku_teksti.Text.Replace(alkup, uusi);
            OmaVahvuusluku_teksti.Text = tmpstr;

            tmpstr = VastustajanVahvuusluku_teksti.Text.Replace(alkup, uusi);
            VastustajanVahvuusluku_teksti.Text = tmpstr;

            tmpstr = TuloksetPistemaaranKanssa_teksti.Text.Replace(alkup, uusi);
            TuloksetPistemaaranKanssa_teksti.Text = tmpstr;

            tmpstr = UusiSELO_teksti.Text.Replace(alkup, uusi);
            UusiSELO_teksti.Text = tmpstr;

            tmpstr = Laske_button.Text.Replace(alkup, uusi);
            Laske_button.Text = tmpstr;

            tmpstr = Kayta_uutta_button.Text.Replace(alkup, uusi);
            Kayta_uutta_button.Text = tmpstr;
        }
        
    }

    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaSelolaskuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaSelolaskuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaSelolaskuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaSelolaskuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaSelolaskuri().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OmaVahvuusluku_teksti;
    private javax.swing.JLabel TuloksetPistemaaranKanssa_teksti;
    private javax.swing.JLabel UusiSELO_teksti;
    private javax.swing.JLabel VastustajanVahvuusluku_teksti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton kaytaUutta_button;
    private javax.swing.JTextField kerroin_output;
    private javax.swing.JTextField keskivahvuus_output;
    private javax.swing.JButton laskeUusiSelo_button;
    private javax.swing.JRadioButton miettimisaika_15_59_Button;
    private javax.swing.JRadioButton miettimisaika_60_89_Button;
    private javax.swing.JRadioButton miettimisaika_alle15_Button;
    private javax.swing.JRadioButton miettimisaika_vah90_Button;
    private javax.swing.JTextField nykyinenSelo_input;
    private javax.swing.JTextField odotustulos_output;
    private javax.swing.JTextField pelimaara_input;
    private javax.swing.JTextField seloEro_output;
    private javax.swing.JRadioButton tappioRadioButton_input;
    private javax.swing.JRadioButton tasapeliRadioButton_input;
    private javax.swing.JTextField tulos_output;
    private javax.swing.JTextField uusiSelo_diff_output;
    private javax.swing.JTextField uusiSelo_output;
    private javax.swing.JTextField uusi_pelimaara_output;
    private javax.swing.JTextField vaihteluvali_output;
    private javax.swing.JTextField vastustajanSelo_input;
    private javax.swing.JRadioButton voittoRadioButton_input;
    // End of variables declaration//GEN-END:variables

}


